GET http://localhost:8080/campanhas
###

GET http://localhost:8080/campanhas/2
###

POST http://localhost:8080/campanhas
Content-Type: application/json

{
    "nome": "Campanha muito braba",
    "inicioCampanha": "2023-10-23",
    "encerramentoCampanha": "2023-10-23",
    "orcamento": "25,000.40"
}
###